SEP3ClientLATEST/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SEP3ClientLATEST.Models
{
    public class Category
        {
            public int CategoryID { get; set; }
            public String CategoryName { get; set; }
            public ICollection<Song> Songs { get; set; }
        }
}

SEP3ClientLATEST/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SEP3ClientLATEST.Models
{
    public class Login
    {
        /// <summary>  
        /// Gets or sets to username address.  
        /// </summary>  
        [Required]
        [Display(Name = "Username")]
        public string Username { get; set; }

        /// <summary>  
        /// Gets or sets to password address.  
        /// </summary>  
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

SEP3ClientLATEST/Models/Registration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SEP3ClientLATEST.Models
{
    public class Registration
    {
        public String Name { get; set; }
        public String Surname { get; set; }
        public DateTime Birthdate { get; set; }
        public int phoneNumber { get; set; }
    }
}

SEP3ClientLATEST/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SEP3ClientLATEST.Models
{
    public class Song
    {
        public int SongID { get; set; }
        public String Title { get; set; }
        public String Artist { get; set; }
        public int VoteAmount { get; set; }
        public int Categoryid { get; set; }
        public Category Category { get; set; }
    }
}

SEP3ClientLATEST/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SEP3ClientLATEST.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SEP3ClientLATEST/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SEP3ClientLATEST.Models;

namespace SEP3ClientLATEST.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty] public Login LoginModel { get; set; }

        /// <summary>  
        /// GET: /Index  
        /// </summary>  
        /// <returns>Returns - Appropriate page </returns>  
        public void OnGet()
        {
        }

        /// <summary>  
        /// POST: /Index/LogIn  
        /// </summary>  
        /// <returns>Returns - Appropriate page </returns>  
        public async Task<IActionResult> OnPostLogIn()
        {
            try
            {
                // Verification.  
                if (ModelState.IsValid)
                {
                    // Verification.  
                    if (LoginModel.Username.Equals("ADMIN") && LoginModel.Password.Equals("ADMIN"))
                    {
                        // Info.  
                        return this.RedirectToPage("/Songs/Index");
                    }
                    else
                    {
                        // Setting.  
                        ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }

            // Info.  
            return this.Page();
        }

        /// <summary>  
        /// POST: /Index/LogIn  
        /// </summary>  
        /// <returns>Returns - Appropriate page </returns>  
        public async Task<IActionResult> OnPostRegister()
        {
            return this.RedirectToPage("/Register/Register");
        }

    }
}

SEP3ClientLATEST/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SEP3ClientLATEST.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SEP3ClientLATEST/Pages/Register/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SEP3ClientLATEST.Models;

namespace SEP3ClientLATEST
{
    public class RegisterModel : PageModel
    {
        [BindProperty] 
        public Registration Register { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPostRegister()
        {
            return this.Page();
        }


    }
}

SEP3ClientLATEST/Pages/Songs/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SEP3ClientLATEST.Models;

namespace SEP3ClientLATEST
{
    public class IndexModel : PageModel
    {
        public List<Song> songList = new List<Song>();

        public String AddSomeSongs()
        {
            songList.Add(new Song()
            {
                Artist = "Artist", Categoryid = 0, SongID = 1,
                Title = "Titlee", VoteAmount = 50
            });
            return "Success";
        }
        public void OnGet()
        {

        }
    }
}

SEP3ClientLATEST/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Log In";
}

<h2>@ViewBag.Title.</h2>

<div class="row">
    <div class="col-md-8">
        <section>
            <form method="post" role="form" class="form-horizontal">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.LoginModel.Username, new { @class = "col-md-2 control-label" })                     
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.LoginModel.Username, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.LoginModel.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.LoginModel.Password, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.LoginModel.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.LoginModel.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button asp-page-handler="LogIn" class="btn btn-primary">Log in</button>
                    <button asp-page-handler="Register" class="btn btn-primary">Register</button>
                </div>
            </div>
            </form>
        </section>
    </div>
</div>

SEP3ClientLATEST/Pages/Register/Register.cshtml
@page
@model SEP3ClientLATEST.RegisterModel
@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)


    <fieldset>
        <legend>User</legend>
        @Html.AntiForgeryToken()
        @if (ViewBag.Message != null)
        {

            <div style="border:solid 1px green">
                @ViewBag.Message
            </div>
        }

        <div class="editor-label">
            @Html.LabelFor(model => model.Register.Surname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Register.Surname)
            @Html.ValidationMessageFor(model => model.Register.Surname)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Register.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Register.Name)
            @Html.ValidationMessageFor(model => model.Register.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Register.phoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Register.phoneNumber)
            @Html.ValidationMessageFor(model => model.Register.phoneNumber)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

SEP3ClientLATEST/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEP3ClientLATEST</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SEP3ClientLATEST</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Songs/Index">Song List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SEP3ClientLATEST - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SEP3ClientLATEST/Pages/Songs/Index.cshtml
@page
@model SEP3ClientLATEST.IndexModel
@{
    ViewData["Title"] = "Song List";
}

<h1>All of the songs that are available right now</h1>
<code>@Model.AddSomeSongs()</code>
<table class="table">
    <thead>
    <tr>
        <th>
            ID
        </th>
        <th>
            Artist
        </th>
        <th>
            Title
        </th>
        <th>
            Vote Amount
        </th>
        <th>
            Genre
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.songList) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SongID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VoteAmount)
            </td>
            <td>
                Unknown
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.SongID">Vote</a> /
            </td>
        </tr>
    }
    </tbody>
</table>